In [ ]:
import numpy as np



1.1. Calculos con una y varias variables

In [2]:
t=2;
x=2*t**3+5*t**2+5;
print(x)

41


In [ ]:
t=2
xo=5
vo=2.5
a=9.8
x=xo+vo*t+a*t**2/2
print(x)

29.6


In [1]:
for t in range(1,9):
  x=2*t**3+5*t**2+5;
  print([t,x]);
  

[1, 12]
[2, 41]
[3, 104]
[4, 213]
[5, 380]
[6, 617]
[7, 936]
[8, 1349]


In [ ]:
t=0;
while t<8:
  t=t+1;
  x=2*t**3+5*t**2+5;
  print([t,x]);


[1, 12]
[2, 41]
[3, 104]
[4, 213]
[5, 380]
[6, 617]
[7, 936]
[8, 1349]


Ejercicios
1. Ejecute las siguientes instrucciones

a = [4 1 3; 2 6 5; 9 7 8]’

b = [9; 6; 8; 5; 2]

c = b(2:5)

d = b(4:-1:1)

e = sort(b)

f = sum(b)

g = max(b)

h = sort(a)

m = sum(a)

n = min(a)


In [ ]:
a=np.array([[4,1,3],[2,6,5],[9,7,8]]).T   ## transpuesta
print(a)
print(a.shape)  ## Filas y columnas de la matriz a


[[4 2 9]
 [1 6 7]
 [3 5 8]]
(3, 3)


In [ ]:
b=np.array([[9],[6],[8],[5],[2]])
print(b)

[[9]
 [6]
 [8]
 [5]
 [2]]


In [ ]:
c=b[1:5]
print(c)

[[6]
 [8]
 [5]
 [2]]


In [ ]:
d = b[np.array([3,2,1,0])]
print(d)

[[5]
 [8]
 [6]
 [9]]


In [ ]:
e=np.sort(b)[::-1]
print(e)

[[2]
 [5]
 [8]
 [6]
 [9]]


In [ ]:
f=np.sum(b)
print(f)

30


In [ ]:
g=np.max(b)
print(g)

9


In [ ]:
h=np.sort(a)
print(h)

[[2 4 9]
 [1 6 7]
 [3 5 8]]


In [ ]:
m=np.sum(A)
print(m)

45


In [ ]:
n=np.min(a)
print(n)

1
